GET http://localhost:5034/api/Players

###
POST http://localhost:5034/api/Players/authenticate
Content-Type: application/json

{
    "login": "admin",
    "password": "Admin64%"
}

###
POST http://localhost:5034/api/Players/register
Content-Type: application/json

{
    "login": "admin",
    "password": "Admin64%",
}

### 
GET http://localhost:5034/api/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTczNzA5MjMzMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDM0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDM0In0.imjC7cWYRYXDy2M90wQ8TELQ90PGy5TRG534EeSTerA

###
POST http://localhost:5034/api/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTczNzA5MjMzMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDM0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDM0In0.imjC7cWYRYXDy2M90wQ8TELQ90PGy5TRG534EeSTerA
Content-Type: application/json
{
    "Name": "Game 1",
}
